In [18]:
%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import seaborn as sns
import warnings
import random
from datetime import datetime, time

warnings.filterwarnings('ignore')

import sqlite3

In [19]:
df = pd.read_csv("train.csv")

In [20]:
df.head()

        id                                               text author
0  id00001  Idris was well content with this resolve of mine.    MWS
1  id00002  I was faint, even fainter than the hateful mod...    HPL
2  id00003  Above all, I burn to know the incidents of you...    EAP
3  id00004  He might see, perhaps, one or two points with ...    EAP
4  id00005  All obeyed the Lord Protector of dying England...    MWS

In [21]:
author_db = 'test_123.sqlite' 
conn = sqlite3.connect(author_db) 
c = conn.cursor()

In [22]:
df.to_sql('project_train',  
             con=conn,         
             if_exists='replace', 
             index=False)

In [23]:
for row in conn.execute("pragma table_info('project_train')").fetchall():
    print (row)

(0, 'id', 'TEXT', 0, None, 0)
(1, 'text', 'TEXT', 0, None, 0)
(2, 'author', 'TEXT', 0, None, 0)

Below query will result out all the column and rows with data from the given table

In [24]:
start = datetime.now()
df_DB_q1 = pd.read_sql('SELECT * FROM project_train', con=conn)
end = datetime.now()
time = end-start
print("Time taken for execution in micro seconds : " , time.microseconds)
df_DB_q1.head()

Time taken for execution in micro seconds :  48047

        id                                               text author
0  id00001  Idris was well content with this resolve of mine.    MWS
1  id00002  I was faint, even fainter than the hateful mod...    HPL
2  id00003  Above all, I burn to know the incidents of you...    EAP
3  id00004  He might see, perhaps, one or two points with ...    EAP
4  id00005  All obeyed the Lord Protector of dying England...    MWS

Below query will select all the data for author "EAP" from the given table

In [25]:
start = datetime.now()
df_DB_q2 = pd.read_sql('SELECT * FROM project_train WHERE author="EAP"', con=conn)
end = datetime.now()
time = end-start
print("Time taken for execution in micro seconds : " , time.microseconds)
df_DB_q2

Time taken for execution in micro seconds :  29519

           id                                               text author
0     id00003  Above all, I burn to know the incidents of you...    EAP
1     id00004  He might see, perhaps, one or two points with ...    EAP
2     id00006  It was difficult, at any given time, to say wi...    EAP
3     id00007  Now, it cannot be maintained, even, that by th...    EAP
4     id00012               They had deposited me in the coffin.    EAP
5     id00015  By ten, I had reason to believe its density co...    EAP
6     id00017  , it will be seen at pp. and , that this illus...    EAP
7     id00021  Besides these things, were seen, on all sides,...    EAP
8     id00024  Wyatt's party arrived in about ten minutes aft...    EAP
9     id00027                You have no reason for concealment.    EAP
10    id00030  Duns, in the meantime, left me little leisure ...    EAP
11    id00032        Had the body been in any respect despoiled?    EAP
12    id00034  His warehouse was the resort of all the princi...    EAP
13    id00050  I touched upon my college indiscretions upon m...    EAP
14    id00051  I have observed that, although the outlines of...    EAP
15    id00053  During the whole of the day I continued to nea...    EAP
16    id00063  Pest spirits, plague goblins, and fever demons...    EAP
17    id00065                  Men lived; and died individually.    EAP
18    id00067  How his sagacity first discovered at all that ...    EAP
19    id00068                He places his head upon the pillow.    EAP
20    id00075  To tear a piece from the interior, where no ed...    EAP
21    id00080   It weighed, altogether, eight pounds six ounces.    EAP
22    id00081  "Contradictories cannot both be true that is, ...    EAP
23    id00082  Of the dungeons there had been strange things ...    EAP
24    id00084  The truth is, I could not help regarding Mrs. ...    EAP
25    id00086         It lay in a remote turret of the building.    EAP
26    id00091  When I had attained that point of the ravine i...    EAP
27    id00099  The larger links of the chain run thus Chantil...    EAP
28    id00113  The figures of fiends in aspects of menace, wi...    EAP
29    id00117  oh, quite a hero perfect desperado no hearts, ...    EAP
...       ...                                                ...    ...
7870  id27891  Somewhat amazed at all this, I made my retreat...    EAP
7871  id27896  And yet how unintelligible is this In all othe...    EAP
7872  id27897  "Your education may now be considered as finis...    EAP
7873  id27900  He was of opinion that the moon was called Ben...    EAP
7874  id27901  And again, and again, in secret communion with...    EAP
7875  id27902  They did not cease, however, importuning me wi...    EAP
7876  id27908  It will then be seen that the movement of the ...    EAP
7877  id27911  The writer professes to have translated his wo...    EAP
7878  id27912  During the now brief interval of darkness a me...    EAP
7879  id27916  Rabble, indeed why these are the noble and fre...    EAP
7880  id27917      The handkerchief bore the name "Marie Rogêt."    EAP
7881  id27921  Yet differently we grew I, ill of health, and ...    EAP
7882  id27924  But in proportion to the progress made in a ga...    EAP
7883  id27925  In this way it was possible to insert the whol...    EAP
7884  id27927   This game is simple, and is played with marbles.    EAP
7885  id27928                              "Sunday, the seventh.    EAP
7886  id27930         "Still" said I, "and why shouldn't she be?    EAP
7887  id27935  Unquestionably, it was in the Earth's dotage t...    EAP
7888  id27939  The vibration of the pendulum was at right ang...    EAP
7889  id27943  These regular interruptions to my slumber caus...    EAP
7890  id27946  Singular to relate, it was once much admired a...    EAP
7891  id27948  At all events he disappeared instantaneously f...    EAP
7892  id27949  In this particular instance, it will be unders...    EAP
7893  id27951  We can only account for its absence by supposi...    EAP
7894  id27954  We feel it advisable only to state, in brief, ...    EAP
7895  id27956  why cause he talk about it in he sleep dat's h...    EAP
7896  id27957  Yet his reasons have not yet been matured into...    EAP
7897  id27959  He has been much admired by Mr. John Neal, and...    EAP
7898  id27966  I still lay quietly, and made effort to exerci...    EAP
7899  id27967  The ultimate body thus escapes our rudimental ...    EAP

[7900 rows x 3 columns]

Below query will sort the result-set in ascending order by author

In [26]:
start = datetime.now()
df_DB_q3 = pd.read_sql('SELECT * FROM project_train ORDER BY author', con=conn)
end = datetime.now()
time = end-start
print("Time taken for execution in micro seconds : " , time.microseconds)
df_DB_q3

Time taken for execution in micro seconds :  72056

            id                                               text author
0      id00003  Above all, I burn to know the incidents of you...    EAP
1      id00004  He might see, perhaps, one or two points with ...    EAP
2      id00006  It was difficult, at any given time, to say wi...    EAP
3      id00007  Now, it cannot be maintained, even, that by th...    EAP
4      id00012               They had deposited me in the coffin.    EAP
5      id00015  By ten, I had reason to believe its density co...    EAP
6      id00017  , it will be seen at pp. and , that this illus...    EAP
7      id00021  Besides these things, were seen, on all sides,...    EAP
8      id00024  Wyatt's party arrived in about ten minutes aft...    EAP
9      id00027                You have no reason for concealment.    EAP
10     id00030  Duns, in the meantime, left me little leisure ...    EAP
11     id00032        Had the body been in any respect despoiled?    EAP
12     id00034  His warehouse was the resort of all the princi...    EAP
13     id00050  I touched upon my college indiscretions upon m...    EAP
14     id00051  I have observed that, although the outlines of...    EAP
15     id00053  During the whole of the day I continued to nea...    EAP
16     id00063  Pest spirits, plague goblins, and fever demons...    EAP
17     id00065                  Men lived; and died individually.    EAP
18     id00067  How his sagacity first discovered at all that ...    EAP
19     id00068                He places his head upon the pillow.    EAP
20     id00075  To tear a piece from the interior, where no ed...    EAP
21     id00080   It weighed, altogether, eight pounds six ounces.    EAP
22     id00081  "Contradictories cannot both be true that is, ...    EAP
23     id00082  Of the dungeons there had been strange things ...    EAP
24     id00084  The truth is, I could not help regarding Mrs. ...    EAP
25     id00086         It lay in a remote turret of the building.    EAP
26     id00091  When I had attained that point of the ravine i...    EAP
27     id00099  The larger links of the chain run thus Chantil...    EAP
28     id00113  The figures of fiends in aspects of menace, wi...    EAP
29     id00117  oh, quite a hero perfect desperado no hearts, ...    EAP
...        ...                                                ...    ...
19549  id27790      Ryland groaned; cold drops stood on his brow.    MWS
19550  id27793  He lost no time in endeavouring to seek him ou...    MWS
19551  id27794  I saw no cause for their unhappiness, but I wa...    MWS
19552  id27797  Experience demonstrated that in a year or two ...    MWS
19553  id27799  Her pallet and easel were now thrown aside; di...    MWS
19554  id27802  She rose on seeing us enter, and when we were ...    MWS
19555  id27806  No wood, however, was placed on the earth, whi...    MWS
19556  id27811  A murmur of approbation followed Elizabeth's s...    MWS
19557  id27817  Look at him ha I see plague She has invested h...    MWS
19558  id27818  His enthusiasm for good which did not exist; h...    MWS
19559  id27823  All delightful things, sublime scenery, soft b...    MWS
19560  id27824  I am now going to claim the protection of some...    MWS
19561  id27827  I shall continue my journal concerning the str...    MWS
19562  id27831  She quitted her native Greece; her father died...    MWS
19563  id27842  He had already bought a farm with his money, o...    MWS
19564  id27844  His depression and anxiety fled; he became all...    MWS
19565  id27849  I shall depart for the latter town in a fortni...    MWS
19566  id27851                      I earned that; I deserved it.    MWS
19567  id27856  I pressed his shoulder to awaken his attention...    MWS
19568  id27887  The time will soon come; grief and famine have...    MWS
19569  id27918  For some time, the spirit of hilarity was kept...    MWS
19570  id27919  Our native oak, as his partisans called him, w...    MWS
19571  id27937     Our little island was filled even to bursting.    MWS
19572  id27938  His limbs were nearly frozen, and his body dre...    MWS
19573  id27947               Adrian was now fifteen years of age.    MWS
19574  id27953  I had before regarded my promise with a gloomy...    MWS
19575  id27958  Fear overcame me; I dared no advance, dreading...    MWS
19576  id27964  So you are about to love her, but do not alrea...    MWS
19577  id27968  "The next morning Felix went out to his work, ...    MWS
19578  id27971  I found myself similar yet at the same time st...    MWS

[19579 rows x 3 columns]

Below query will given distinct (different) values of author column

In [27]:
start = datetime.now()
df_DB_q4 = pd.read_sql('SELECT DISTINCT author FROM project_train', con=conn)
end = datetime.now()
time = end-start
print("Time taken for execution in micro seconds : " , time.microseconds)
df_DB_q4.head()

Time taken for execution in micro seconds :  15052

  author
0    MWS
1    HPL
2    EAP

Below query will give the count of the text by each author

In [28]:
start = datetime.now()
df_DB_q5 = pd.read_sql('SELECT author, count(text) FROM project_train GROUP BY author', con=conn)
end = datetime.now()
time = end-start
print("Time taken for execution in micro seconds : " , time.microseconds)
df_DB_q5.head()

Time taken for execution in micro seconds :  25028

  author  count(text)
0    EAP         7900
1    HPL         5635
2    MWS         6044

In [29]:
from google.cloud import storage
import os

In [30]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r"My First Project-5c8e9f0c107a.json"

In [31]:
client = storage.Client()

In [32]:
bucket = client.get_bucket('test_backup-db')

In [33]:
blob = bucket.blob('test_123.sqlite')

In [34]:
blob.upload_from_filename('author_db.sqlite')